### ISSUE TITLE
Ymir and WoW crash on wow login ymir_retail_10.2.5.53262 (PTR)

### ISSUE THREAD

**Issue by imlost88** [TrinityCore/ymir#10]
Hi,
Ymir and wow crash on wow login 

Ncap 1.79
ymir_retail.exe rename to ymir_ptr.exe
cache ptr clear
wow ptr 10.2.5.53262

![Capture d'écran 2024-02-15 191106](https://github.com/TrinityCore/ymir/assets/131078921/7dd77cb7-08bb-4bb8-a8c4-e4d10edf4170)

**Comment by mdX7** [comment]
You can't simply use retail client for PTR by renaming it. PTR and Retail clients are different binaries and need different sniffers
