### ISSUE TITLE
11.0.2.56819 and 11.0.5.57212 new version Retail crash !

### ISSUE THREAD

**Issue by luodaoyi** [TrinityCore/ymir#12]
![Snipaste_2024-10-23_23-50-52](https://github.com/user-attachments/assets/2d140cf2-b376-4011-a931-612412ab09dd)

**Comment by luodaoyi** [comment]
error on 11.0.5.57212
![1](https://github.com/user-attachments/assets/b51fb5c8-212b-46ea-9fd5-c5d051685dae)

**Comment by mdX7** [comment]
CN builds for retail are currently not supported (Wow.exe is explicitly different compared to other locales)
