### ISSUE TITLE
TBC PTR support

### ISSUE THREAD

**Issue by Nytanath** [TrinityCore/ymir#2]
Hello! Sorry if this appears needy or whiny, but I was wondering if the TBC PTR will be supported again eventually. It was very useful for me and probably others that don't currently play on Retail too.

**Comment by mdX7** [comment]
I actually just forgot to update it since in my mind PTR was still on a test build haha

uploaded current one here https://github.com/TrinityCore/ymir/releases/tag/2.5.4.42873

**Comment by Nytanath** [comment]
Thanks a lot!
