### ISSUE TITLE
ymir does not work with VPN

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/ymir#3]
They should take this into account, because there are countries that cannot use the ymir, because they must use VPN to enter Blizzard. I think the solution should not be so difficult.
I explain: With vpn and ymir you can enter the game and do everything but ymir generates the empty .pkt file.

**Comment by osleyder85** [comment]
Do you know any VPN that you can recommend?

**Comment by mdX7** [comment]
ymir works with VPNs since last update. Tested WireGuard VPN
