### ISSUE TITLE
49679 release don't work for latest game build 49741

### ISSUE THREAD

**Issue by humanpride** [TrinityCore/ymir#6]
The program exits with an error and does not create the dump/ folder

I can't copy text, here is a screenshot:
https://paste.pics/O6PUA

First line translate:
`GetWoWProcessList(): System.ComponentModel.Win32Exception (299): Request ReadProcessMemory or WriteProcessMemory was only partially fulfilled.`

Fix it in the next release, please.

**Comment by mdX7** [comment]
https://github.com/TrinityCore/ymir/releases/tag/10.1.0.49741
