### ISSUE TITLE
3.4.2.50664 support.

### ISSUE THREAD

**Issue by lineagedr** [TrinityCore/ymir#8]
Hey, are there any plans on updating ymir to version 3.4.2.50664?

**Comment by neifion-00000000** [comment]
https://github.com/TrinityCore/ymir/releases/tag/3.4.2.50664

idk what happened that it didn't update the front page like normal

**Comment by lineagedr** [comment]
LOL thanks I have no idea why that is

![image](https://github.com/TrinityCore/ymir/assets/12139798/6f71f4d9-3442-4c52-be02-bab8ca9f81fc)
