### ISSUE TITLE
Ymir terminate while WoW login (ymir_retail_10.2.0.52808)

### ISSUE THREAD

**Issue by NumboWoW** [TrinityCore/ymir#9]
Npcap-1.78 is installed with "Npcap in WinPcap API-compatible Mode" and **not** restricted to admin only.
Deleting cache and starting Ymir with the batch provided - so far so good.

Starting WoW with wow.exe does work until the point where you enter credentials and login.
Somewhere in the login process ymir (and wow) terminate with the following output.

The opcode shown always changes on a new try (I guess because the termination already started?)

In the other open issue I found the same problem at the top but no solution did work (starting ymir/wow 20 times in a row and even reboot)

![ymir_crash](https://github.com/TrinityCore/ymir/assets/101930210/bc053502-7d70-4479-a78d-ce26ed8f236e)

**Comment by ratkosrb** [comment]
You have to keep trying until it works. This happens a lot to me, but eventually it works.

**Comment by CraftedRO** [comment]
Same issue here.

**Comment by NumboWoW** [comment]
The updated release seem to fix the problem. (update 1)
At least I can now happily sniff, great work 👍🏽
